USE ships;

-- Посочете заявката, която извежда всички държави, които имат както класове с по-малко от 9 оръдия (numguns), така и класове с
-- над 12 оръдия:

SELECT DISTINCT COUNTRY FROM CLASSES WHERE NUMGUNS < 9 AND NUMGUNS > 12;

SELECT DISTINCT C1.COUNTRY FROM CLASSES C1 JOIN CLASSES C2 ON C1.COUNTRY = C2.COUNTRY WHERE C1.NUMGUNS < 9 AND C2.NUMGUNS > 12; -- ✓

SELECT COUNTRY FROM CLASSES WHERE NUMGUNS < 9
UNION
SELECT COUNTRY FROM CLASSES WHERE NUMGUNS > 12;

SELECT DISTINCT COUNTRY FROM CLASSES WHERE NUMGUNS < 9 AND COUNTRY = (SELECT COUNTRY FROM CLASSES WHERE NUMGUNS > 12)

-- Посочете заявката, която за всяка държава, участвала в не повече от 4 битки, извежда името й и броя битки, в които е участвала.
-- Ако дадена държава няма нито един кораб или не е участвала в нито една битка, за нея да извежда 0.

SELECT COUNTRY, COUNT(DISTINCT BATTLE) FROM CLASSES C, SHIPS S, OUTCOMES O WHERE C.CLASS=S.CLASS AND S.NAME=O.SHIP
GROUP BY COUNTRY HAVING COUNT(DISTINCT O.BATTLE) < 4;

SELECT COUNTRY, COUNT(O.BATTLE) AS NUM_BATTLES FROM CLASSES C LEFT JOIN SHIPS S ON C.CLASS=S.CLASS
LEFT JOIN OUTCOMES O ON S.NAME=O.SHIP GROUP BY COUNTRY HAVING COUNT(O.BATTLE) < 4; -- ✓

SELECT COUNTRY, COUNT(DISTINCT BATTLE) FROM OUTCOMES JOIN SHIPS ON NAME=SHIP RIGHT JOIN CLASSES ON CLASSES.CLASS=SHIPS.CLASS
GROUP BY COUNTRY HAVING COUNT(DISTINCT OUTCOMES.BATTLE) <= 3;

SELECT C.COUNTRY, COUNT(O.BATTLE) FROM CLASSES AS C INNER JOIN SHIPS AS S ON C.CLASS=S.CLASS
LEFT OUTER JOIN OUTCOMES AS O ON S.NAME=O.SHIP WHERE COUNT(O.BATTLE) <= 3

-- ______________________________________________

USE movies;

-- Да се посочи заявката, извеждаща всички актриси, които не са играли в нито един филм с име, започващо с буквата А.
-- Актриси, за които в базата от данни няма информация за техните участия, също трябва да бъдат изведени.

SELECT DISTINCT NAME FROM MOVIESTAR LEFT JOIN STARSIN ON NAME = STARNAME WHERE GENDER = 'F' AND MOVIETITLE NOT LIKE 'A%';

SELECT NAME FROM MOVIESTAR JOIN STARSIN ON STARNAME = NAME WHERE GENDER = 'F' AND MOVIETITLE LIKE 'A%' GROUP BY NAME
HAVING COUNT(*) = 0;

SELECT MS.NAME FROM MOVIESTAR MS WHERE MS.GENDER = 'F' AND NOT EXISTS
(SELECT 1 FROM STARSIN SI WHERE SI.STARNAME = MS.NAME AND SI.MOVIETITLE LIKE 'A%'); -- ✓

SELECT NAME FROM MOVIESTAR WHERE GENDER = 'F' AND NAME IN (SELECT DISTINCT STARNAME FROM STARSIN WHERE NOT MOVIETITLE LIKE 'A%');

-- Да се посочи заявката, която за всяка филмова звезда (без значение от пола), родена преди 1990 г., извежда възрастта, на която
-- е играла за първи път във филм. Звезди, за които няма информация за техните участия във филми, не трябва да бъдат извеждани.

SELECT NAME, MIN( MOVIEYEAR - YEAR(BIRTHDATE) ) AS DEBUT_AGE FROM MOVIESTAR JOIN STARSIN ON NAME = STARNAME
WHERE YEAR(BIRTHDATE) < 1990 GROUP BY NAME;

SELECT NAME, MIN(MOVIEYEAR) - YEAR(BIRTHDATE) AS DEBUT_AGE FROM MOVIESTAR JOIN STARSIN ON NAME = STARNAME
WHERE YEAR(BIRTHDATE) < 1990 GROUP BY NAME;

SELECT NAME, MIN(MOVIEYEAR) - YEAR(BIRTHDATE) AS DEBUT_AGE FROM MOVIESTAR
LEFT JOIN STARSIN ON NAME = STARNAME AND YEAR(BIRTHDATE) < 1990 GROUP BY NAME HAVING MIN(MOVIEYEAR);

SELECT DISTINCT MS.NAME, MOVIEYEAR - YEAR(BIRTHDATE) AS DEBUT_AGE FROM MOVIESTAR MS, STARSIN
WHERE MS.NAME = STARNAME AND YEAR(BIRTHDATE) < 1990 HAVING MOVIEYEAR <= ALL
(SELECT MOVIEYEAR FROM STARSIN SI WHERE SI.STARNAME = MS.NAME);